# Registration flow steps
REGISTER_EMAIL = 'REGISTER_EMAIL'
VERIFY_EMAIL = 'VERIFY_EMAIL'
CREATE_PASSWORD = 'CREATE_PASSWORD'
CREATE_USERNAME = 'CREATE_USERNAME'
RESEND_VERIFICATION_CODE = 'RESEND_VERIFICATION_CODE'

REGISTRATION_STEPS = [
    REGISTER_EMAIL,
    VERIFY_EMAIL,
    CREATE_PASSWORD,
    CREATE_USERNAME,
]
