# Generated by Django 5.0 on 2024-01-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
