# Generated by Django 5.0 on 2024-01-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_user_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetUsernameToken',
        ),
    ]
